# Generated by Django 2.0.6 on 2019-04-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_PATH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('userPath', models.CharField(max_length=256)),
                ('loginTime', models.CharField(blank=True, max_length=1024)),
                ('stayingTime', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
